version: '3.8'

services:
  # Servicio de Base de Datos
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  # Servicio de la API
  api:
    build: .
    container_name: todo-api
    restart: always
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/tododb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  postgres_data: